apiVersion : apps/v1
kind: Deployment
metadata:
  name: javadeployare 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javadeployare
  template:
    metadata:
      labels:
        app: javadeployare 
    spec:
      containers:
        - name: javadeployare 
          image: kcscr.azurecr.io/javadeployare
          ports:
          - containerPort: 80